feat: Implementação de componente global de loading com controle via store
jonatasoli/fast-ecommerce-template pull request #4
Opened 2024-10-28 15:42 UTC by Jpcampos123

Criada a store isLoading com funções showLoading e hideLoading para controle global do estado de loading.
Adicionado o componente Loading.svelte para exibir um spinner durante o carregamento.
Integrado o componente Loading ao +layout.svelte para controlar sua visibilidade.
Qualquer componente pode iniciar ou parar o loading usando as funções da store.

2024-11-13 16:36 UTC, jonatasoli requested changes
Alguns pontos apenas para esclarecer.

2024-11-13 16:36 UTC, jonatasoli commented on src/lib/components/Header/Header.svelte
> +			placeholder="Digite o que você procura"
o placeholder não deveria ficar no i18 também?

2024-11-13 16:36 UTC, jonatasoli commented on static/favicon.png
pode até deixar por hora, mas o ideal aqui era pegar de uma url, talvez deixar no geral lá no admin uma config pra subir o favicon.png e ai recuperar a url dessa config aqui.

2024-11-14 16:47 UTC, Jpcampos123 commented on static/favicon.png
ok

2024-12-06 19:16 UTC, merged